name: CD Pipeline

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed
    branches: [main, workflow]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Digital Ocean VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            echo "Connected. Creating test directory..."
            cd /root/projects/Our-Shelves || (mkdir -p /root/projects/Our-Shelves && cd /root/projects/Our-Shelves)
            
            # Clone or pull latest code
            if [ -d ".git" ]; then
              echo "Pulling latest changes..."
              git pull origin main
            else
              echo "Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git .
            fi

            echo "Setting up production environment..."
            printf "%s" "${{ secrets.VM_ENV }}" > .env

            # Check to see if env has been correctly added
            if [ -z "${{ secrets.VM_ENV }}" ]; then
            echo "ENV secret is EMPTY"
            else
              echo "ENV secret is SET (hidden for security)"
            fi

            echo "Stopping existing containers..."
            docker compose down -v

            echo "Building and starting containers"
            docker compose up -d --build

            echo "Verifying deployment..."
            docker compose ps

            echo "Cleaning up old Docker images..."
            docker image prune -f
            
            
    