name: CI/CD Pipeline

on: 
  push:
      branches: [workflow]
  pull_request:
      branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Backend Unit Tests
        run: |
          cd backend
          npm i
          npm test
      - name: Backend Integration Tests
        run: |
          cd backend
          npm i
          npm run test:integration
    
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Frontend Unit Tests
        run: |
          cd frontend
          npm i
          npm test
          
  end-to-end-tests:
    runs-on:  ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps: 
      - uses: actions/checkout@v3

      - name: Setting up e2e tests 
        run: |
          cd frontend 
          npm i 
          npm run dev

      - name: Running e2e tests 
        run: | 
          cd frontend
          npx cypress run

