name: CI/CD Pipeline

on: 
  push:
      branches: [workflow]
  pull_request:
      branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Backend Tests
        run: |
          cd backend
          npm i
          echo "Running backend unit tests"
          npm test
          echo "Running backend integration tests"
          npm run test:integration
          
            
            
